START TRANSACTION;

CREATE TABLE IF NOT EXISTS artist (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    bio VARCHAR(500),
    email VARCHAR(255) NOT NULL,
    profile_pic VARCHAR(255),
    created_at DATETIME DEFAULT NOW(),
    updated_at DATETIME DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);
    
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Bruno Mars', '15x time GRAMMY Award winner Bruno Mars is one of the best-selling artists of all time. DOO-WOPS & HOOLIGANS marked the landmark debut of a remarkable new artist. The album – which peaked at #3 on the Billboard 200 – has gone on to achieve global album equivalent sales of 15.5 million. Now boasting more than 7.8 billion total streams, DOO-WOPS & HOOLIGANS is certified RIAA 6X platinum, the longest-charting debut album on Top 200 and #4 longest-running of all time. His most recent album, the crit', 'bruno_mars@prosolutions.com', 'https://i.scdn.co/image/ab6761610000e5ebc36dd9eb55fb0db4911f25dd');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('2Pac', 'A natural ability to appeal to hedonists and revolutionaries alike, combined with charismatic star power and unapologetic threat, made 2Pac one of the most fascinating and successful rappers of the ''90s. These qualities, along with his oft-imitated but never replicated flow, have made him an enduring influence on hip-hop decades after his tragic death. 2Pac emerged in 1991 as an ancillary member of , appearing on the group''s Top Ten R&B/hip-hop single "Same Song," and by the end of the year earn', '2pac@eliteinsights.org', 'https://i.scdn.co/image/ab6761610000e5eb7f5cc432c9c109248ebec1ac');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Mc IG', 'MC, compositor e empresário, IG é cria da Vila Medeiros, Zona Norte de São Paulo. Igor ou Guilherme - questionamento que deixa a encargo dos fãs -, o artista tem uma relação de extrema proximidade com a sua quebrada, lugar onde guarda com muito carinho e enaltece em suas músicas.\nAinda garoto e antes de ser MC, IG já vendia suas composições para outros artistas. Enquanto cantor, o HIT que alavancou sua carreira foi “3 dias virado”, música lançada há dois anos que conta com mais de 300 milhões d', 'mc_ig@strategicedge.net', 'https://i.scdn.co/image/ab6761610000e5ebd9fee554b5ae9ad3427c0320');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Taylor Swift', 'All’s fair in love and poetry… New album THE TORTURED POETS DEPARTMENT. Out now!', 'taylor_swift@globalimpact.co', 'https://i.scdn.co/image/ab6761610000e5ebe672b5f553298dcdccb0e676');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('James Fortenberry', '1,229\nFollowers\n9,339\nMonthly Listeners', 'top_hit_artists@optimindgroup.biz', 'https://i.scdn.co/image/ab67616d0000b27384badb0730bf37054348f2b8');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('MC Ryan SP', 'MC Ryan SP, é um jovem artista do segmento Funk que, através de suas composições criativas, irreverentes e combativas, transita por diversos estilos dentro do ritmo, criando, inclusive, um estilo próprio de criação.  Natural de São Paulo, Ryan é cria da Favela Zaki Narchi, região carente da zona norte da capital, próxima aos bairros do Carandiru e Santana. O artista exalta o local de onde veio em suas canções e no seu cotidiano, sempre levantando a bandeira de que é possível vencer através do Fu', 'mc_ryan_sp@venturepinnacle.io', 'https://i.scdn.co/image/ab6761610000e5ebbaaac18ba160be41208bca04');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Lady Gaga', 'Academy Award and 14-time GRAMMY-winner Lady Gaga is a one-of-a-kind artist and performer. She has amassed an outstanding 110 million global album sales, 175 billion streams, and 758 million song consumption units, making her one of the best-selling musicians of all time. Her most recent pop album, Chromatica, became her sixth consecutive #1 on the Billboard 200 chart, making her the first female artist to achieve this over a ten-year period (2011-2020). Gaga''s collaboration with Ariana Grande o', 'lady_gaga@apexinnovate.tech', 'https://i.scdn.co/image/ab6761610000e5ebaadc18cac8d48124357c38e6');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Top Drawer', '1,787\nFollowers\n59,390\nMonthly Listeners', 'top_drawer@primeadvisors.info', 'https://i.scdn.co/image/ab67616d0000b273a6cee6ca44da1c96565ae106');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('BK', 'Uma das vozes mais contundentes dentro do rap nacional, Abebe Bikila, mais conhecido como BK’, é um rapper carioca que carrega em suas rimas as vivências de um corpo negro dentro das grandes metrópoles. Seus versos, além de críticas sociais e conquistas, também narram um outro lado do rolê, trazendo as situações mais nuas e cruas possíveis.\nEm 2021, o cantor fundou o seu próprio selo, Gigantes, por onde lançou o EP Cidade do Pecado. O nome dado ao selo faz referência ao seu segundo trabalho de ', 'bk@coreachievers.co', 'https://i.scdn.co/image/ab6761610000e5ebaedd984d97865aef05fb6060');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('The Weeknd', 'The Weeknd took over pop music & culture on his own terms filtering R&B, Pop,& hip-hop through an ambitious widescreen lens. The multi-platinum 3X GRAMMY Award winner has emerged as one of the most successful & significant artists of the modern era. 2012’s 3X platinum collated 3 breakout mixtapes—House of Balloons, Thursday & Echoes of Silence—into his 1st chart-topping collection followed by his debut LP in 2013. Two years later, “Earned It (Fifty Shades of Grey)” won “Best R&B Performance” & r', 'the_weeknd@summitascent.org', 'https://i.scdn.co/image/ab6761610000e5eb9e528993a2820267b97f6aae');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('William Mullins', '43\nFollowers\n2\nMonthly Listeners', 'top_artists@futureforward.net', 'https://i.scdn.co/image/ab67616d0000b27312ffbeb5cdff376eedb7ac6f');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Veigh', 'Criado nas comunidades de Itapevi, Zona Oeste de São Paulo, Thiago Veigh é uma das novas e mais promissoras vozes da cena brasileira de Trap/RnB, apresentando sempre muita versatilidade em suas composições.', 'veigh@quantumleap.com', 'https://i.scdn.co/image/ab6761610000e5ebc97ae4af9d554b04097954b5');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Billie Eilish', 'Billie Eilish remains one of the biggest stars to emerge in the 21st century. Her third studio album, HIT ME HARD AND SOFT features 10 tracks written and recorded in her hometown of Los Angeles, with her brother and producer FINNEAS. In 2019, her debut album WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? debuted at No. 1 in 18 countries, and was the most streamed album of that year. In 2021, her sophomore album ''Happier Than Ever’ debuted at #1 in 20 countries. Both albums were critically acclaimed wo', 'billie_eilish@truenorthconsult.co', 'https://i.scdn.co/image/ab6761610000e5eb4a21b4760d2ecb7b0dcdc8da');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Carole Soileau', '95\nFollowers\n9\nMonthly Listeners', 'top_artists@elevatesuccess.org', 'https://i.scdn.co/image/ab67616d0000b27385911bf8afaa93c0ea476ecf');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Xamã', 'Xamã disparou e vem dominando os charts dos serviços de streaming. Nascido em Sepetiba, zona oeste do Rio de Janeiro, Geizon Carlos da Cruz Fernandes - nome de batismo - tem em seu currículo três álbuns, três EP’s e soma milhões de ouvintes mensais nas plataformas digitais.', 'xamã@masterfulresults.net', 'https://i.scdn.co/image/ab6761610000e5eb367afe9e5b30fbb6a67a8807');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Kendrick Lamar', 'One of the most acclaimed artists of his generation, hip-hop or otherwise, Kendrick Lamar is known for his top-tier lyricism, virtuosic microphone command, and sharp conceptual vision. His talents have translated to a rare combination of continuous chart feats and critical acclaim, plus respect and support from the rappers who paved the way for his advancement. The Compton native started in his teens and hit his creative and commercial stride in the 2010s, during which he authored the multi-plat', 'kendrick_lamar@premieralliance.com', 'https://i.scdn.co/image/ab6761610000e5eb39ba6dcd4355c03de0b50918');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Top Replays', '36\nFollowers\n1\nMonthly Listeners', 'top_artists@synergypath.io', 'https://i.scdn.co/image/ab67616d0000b2738e78cab5dcc4bde215026826');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('MC PH', 'Pedro Henrique de Oliveira Rocha, conhecido artisticamente como MC PH, tem 27 anos e nasceu na Zona Norte de São Paulo - mais precisamente na Vila Medeiros. O jovem sonhador se descobriu como cantor e compositor quando tinha apenas 11 anos, em 2010, e lançou sua primeira produção no YouTube no ano seguinte.\nApós um período de persistência e muita dedicação, o MC foi notado pelo empresário Alexandre Santana - o Gugu - que o juntou a outros MCs da Zona Norte da capital para formar o grupo 4M, uma', 'mc_ph@brightfuturesolutions.tech', 'https://i.scdn.co/image/ab6761610000e5ebbeeaaa1e723c05117134bb57');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Bad Bunny', 'Bad Bunny is a young urban music singer, rapper and producer originally from Puerto Rico. This talented artist has demonstrated his already overwhelming power, influence and demand with completely sold-out concerts all over Europe, Latin America and the U.S.  Some of his most recognized singles include “Soy Peor," "Diles," "Tu No Metes Cabra," "Chambea" and Mia thats out with Drake. Bad Bunny has had a short but stunning career with colossal amounts of success', 'bad_bunny@catalystgrowth.info', 'https://i.scdn.co/image/ab6761610000e5eb81f47f44084e0a09b5f0fa13');
INSERT INTO artist (name, bio, email, profile_pic) VALUES ('Crystal White', '255\nFollowers\n2\nMonthly Listeners', 'top_artists@infinitepossibilities.biz', 'https://i.scdn.co/image/ab67616d0000b2737b76d664fe55ab3c6ff996bd');
COMMIT;
